# Generated by Django 2.1.3 on 2019-04-05 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_business',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 9, 34, 33, 823809)),
        ),
        migrations.AlterField(
            model_name='accepted_business',
            name='b_applied_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 9, 34, 33, 823809)),
        ),
        migrations.AlterField(
            model_name='business',
            name='b_applied_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 9, 34, 33, 808208)),
        ),
        migrations.AlterField(
            model_name='business_loan_application',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 9, 34, 33, 808208)),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disburse_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 9, 34, 33, 823809)),
        ),
        migrations.AlterField(
            model_name='virtualpayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 5, 9, 34, 33, 823809)),
        ),
    ]
